"""The four host adapters (P19 Claude Code, P20 Codex, P21 Cursor, P22 Antigravity). Packaging only (D-042)."""
import json

from .. import __version__
from .base import DESCRIPTION, Adapter, entry_skills

AUTHOR = {"name": "Vikhyath", "url": "https://github.com/Vikhyath-thelazycoder"}
REPO = "https://github.com/Vikhyath-thelazycoder/vikhyath-ai-engineering-os"
NAME = "vikhyath-ai-engineering-os"


def _json(data) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


class ClaudeCode(Adapter):
    """Plugin from this repo via the Claude marketplace; skills/ agents/ hooks/ are auto-discovered."""
    host = "claude-code"

    def repo_files(self):
        hooks = (self.root / "hooks" / "hooks.json").read_text(encoding="utf-8") \
            if (self.root / "hooks" / "hooks.json").is_file() else ""
        return {".claude-plugin/plugin.json": _json({
                    "name": NAME, "version": __version__, "description": DESCRIPTION, "author": AUTHOR,
                    "homepage": REPO, "repository": REPO, "license": "MIT"}),
                "hooks/hooks.json": hooks}

    HOW = ("claude plugin marketplace add Vikhyath-thelazycoder/vikhyath-ai-engineering-os && "
           "claude plugin install vikhyath-ai-engineering-os@vikhyath-marketplace")

    def installed(self):
        reg = self.user_home / ".claude" / "plugins" / "installed_plugins.json"
        if not reg.is_file():
            return {"installed": False, "where": str(reg), "how": self.HOW}
        data = json.loads(reg.read_text(encoding="utf-8"))
        plugins = data.get("plugins", data)
        hits = {k: v for k, v in plugins.items() if k.startswith(NAME + "@")}
        entry = next(iter(hits.values()), None)
        if isinstance(entry, list):
            entry = entry[0] if entry else None
        return {"installed": bool(hits), "where": str(reg), "entries": sorted(hits),
                "version": (entry or {}).get("version") if isinstance(entry, dict) else None, "how": self.HOW}


class Codex(Adapter):
    """`.codex-plugin/plugin.json` (skills dir) + `.agents/plugins/marketplace.json` (H-4: `codex plugin add`)."""
    host = "codex"

    def repo_files(self):
        return {
            ".codex-plugin/plugin.json": _json({
                "name": NAME, "version": __version__, "description": DESCRIPTION, "author": AUTHOR,
                "homepage": REPO, "repository": REPO, "license": "MIT",
                "keywords": ["ai", "engineering", "routing", "skills", "verification", "codex"],
                "skills": "./skills/",
                "interface": {"displayName": "Vikhyath AI Engineering OS",
                              "shortDescription": "Deterministic routing, budgeted context and local test-first "
                                                  "verification for engineering work.",
                              "longDescription": DESCRIPTION, "developerName": "Vikhyath", "category": "Coding",
                              "capabilities": ["Interactive", "Read"], "brandColor": "#6C5CE7"}}),
            ".agents/plugins/marketplace.json": _json({
                "name": "vikhyath-marketplace", "interface": {"displayName": "Vikhyath Plugin Marketplace"},
                "plugins": [{"name": NAME, "version": __version__, "description": DESCRIPTION, "source": "./"}]}),
        }

    def installed(self):
        cache = self.user_home / ".codex" / "plugins" / "cache"
        hits = sorted(str(p) for p in cache.glob(f"*/{NAME}*")) if cache.is_dir() else []
        return {"installed": bool(hits), "where": str(cache), "entries": hits,
                "how": "codex plugin marketplace add Vikhyath-thelazycoder/vikhyath-ai-engineering-os && "
                       "codex plugin add vikhyath-ai-engineering-os@vikhyath-marketplace"}


class Cursor(Adapter):
    """User-level skills in ~/.cursor/skills/ (central; nothing written into projects, H-1)."""
    host = "cursor"

    def skills_target(self):
        return self.user_home / ".cursor" / "skills"


ANTIGRAVITY_SKILL = """---
name: vikhyath-os
description: Vikhyath AI Engineering OS for Antigravity — route every task with `vikhyath route`, load only the routed capabilities, follow the lifecycle and verify locally with `vikhyath verify`.
---

# Vikhyath AI Engineering OS (Antigravity)

Generated by `vikhyath adapters render` from the canonical entry skills (`skills/vikhyath-*`); do not edit by hand.

1. Start: `vikhyath bootstrap --host antigravity` (compact project state, plan pointer, capability index).
2. Route: `vikhyath route "<request>"`; load only what it selects with `vikhyath context <id>…`.
3. Follow the route's `lifecycle` and `impact` steps; verify with `vikhyath verify` and record evidence.

Domain guides (same text on every host): {skills}.

Verification policy: local test-first (`config/verification.yaml`) — no browser, Chrome DevTools, screenshots or MCP.
"""


class Antigravity(Adapter):
    """Project-skill file in this repo (when the repo is the plugin) + user-level skills in ~/.gemini/config/skills/."""
    host = "antigravity"

    def repo_files(self):
        names = ", ".join(f"`{n}`" for n in entry_skills(self.root))
        return {".agents/skills/vikhyath-os/SKILL.md": ANTIGRAVITY_SKILL.replace("{skills}", names)}

    def skills_target(self):
        return self.user_home / ".gemini" / "config" / "skills"


ADAPTERS = {"claude-code": ClaudeCode, "codex": Codex, "cursor": Cursor, "antigravity": Antigravity}


def get(host: str, **kw) -> Adapter:
    return ADAPTERS[host](**kw)


def all_adapters(**kw):
    return [cls(**kw) for cls in ADAPTERS.values()]
