#!/usr/bin/env python3
"""Render docs/audit/05_CAPABILITY_MATRIX.md and 06_DOMAIN_MAPPING.md from P2 evidence.

Run after tools/audit/extraction_matrix.py. Requires PyYAML.
"""
import csv
import glob
import json
import os
import sys
from collections import defaultdict

import yaml

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, ROOT)
from agylite.registry.loader import load_cards, load_domains  # noqa: E402
AUDIT = os.path.join(ROOT, "docs", "audit")
EVIDENCE = os.path.join(AUDIT, "evidence")
BUNDLED = {"COPY", "ADAPT", "WRAP", "PRESERVE"}
LICENSES = {
    "addy": "MIT", "agency": "MIT", "beacon": "MIT", "beyondseo": "MIT", "brag": "MIT", "ecc": "MIT",
    "graphify": "Apache-2.0 (+MIT)", "gstack": "MIT (+Apache-2.0 notices)", "karpathy": "MIT (declared)",
    "opendesign": "Apache-2.0", "ponytail": "MIT", "taste": "MIT", "uiuxpromax": "MIT", "unlazy": "MIT",
    "appllama": "MIT",
}


def group_prefix(path):
    parts = path.split("/")
    if len(parts) == 1:
        return path
    if parts[0] in {"skills", "agents", "design-systems", "playbooks", "rules", "craft", "src"} and len(parts) > 2:
        return "/".join(parts[:2]) + "/"
    if len(parts) > 2 and parts[0] in {".claude"}:
        return "/".join(parts[:3]) + "/"
    return parts[0] + "/" if len(parts) > 1 else path


def main():
    caps = load_cards()
    domains = load_domains()
    with open(os.path.join(EVIDENCE, "upstream-staging-snapshot.yaml"), encoding="utf-8") as f:
        pins = {k: v["head"] for k, v in yaml.safe_load(f)["snapshots"].items()}
    with open(os.path.join(EVIDENCE, "extraction-summary.json"), encoding="utf-8") as f:
        summary = json.load(f)

    rows = defaultdict(lambda: [0, 0])
    for tsv in sorted(glob.glob(os.path.join(EVIDENCE, "extraction-matrix", "*.tsv"))):
        repo = os.path.basename(tsv)[:-4]
        with open(tsv, encoding="utf-8") as f:
            for r in csv.DictReader(f, delimiter="\t"):
                if r["decision"] in BUNDLED:
                    key = (repo, r["capability"], group_prefix(r["path"]), r["decision"])
                    rows[key][0] += 1
                    rows[key][1] += int(r["bytes"])

    out = ["# 05 — Capability Matrix (spec §61)", "",
           "*Generated by `tools/audit/render_matrix_docs.py` from the per-file extraction matrix. Do not edit by hand.*", "",
           "Every bundled upstream component appears below, grouped by source path prefix. The per-file rows (all 26,588 upstream files, "
           "including EXCLUDE/REFERENCE with reason codes) are in [evidence/extraction-matrix/](evidence/extraction-matrix/). "
           "Destination is the target capability; the physical bundle layout is fixed in P3 (`20_TARGET_ARCHITECTURE_RECOMMENDATION.md`).", "",
           "| Source | Capability (destination) | Source path | Files | KB | Integration | Runtime | License | SHA |",
           "|---|---|---|---:|---:|---|---|---|---|"]
    for (repo, cap, prefix, dec), (n, b) in sorted(rows.items(), key=lambda kv: (kv[0][1], kv[0][0], kv[0][2])):
        runtime = caps.get(cap, {}).get("runtime_type", "")
        out.append(f"| {repo} | {cap} | `{prefix}` | {n} | {b / 1024:.1f} | {dec} | {runtime} | {LICENSES[repo]} | `{pins[repo][:7]}` |")
    tot_n = sum(v[0] for v in rows.values())
    tot_b = sum(v[1] for v in rows.values())
    out += ["", f"**Total bundled: {tot_n} files, {tot_b / 1e6:.1f} MB** across {len({k[1] for k in rows})} capabilities."]
    with open(os.path.join(AUDIT, "05_CAPABILITY_MATRIX.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    capsum = summary["capabilities"]
    out = ["# 06 — Domain Mapping (spec §5–12)", "",
           "*Generated by `tools/audit/render_matrix_docs.py` from the capability cards (`capabilities/**/card.yaml`) and the extraction summary.*", "",
           "Domains are the user-facing architecture; upstream repositories appear only as provenance. "
           "`On-disk est. tokens` = bundled bytes ÷ 4 (**estimate**, spec §46). It is the size available to load, "
           "not what is loaded: the context engine (P9) loads L1 summaries first and L2/L3 files only when selected.", ""]
    for domain, dd in domains.items():
        out += [f"## {domain}", "", dd["purpose"], "",
                "| Capability | Purpose | Sources | Files | KB | On-disk est. tokens | Context | Runtime | Network | Browser | Origin | Uses |",
                "|---|---|---|---:|---:|---:|---|---|---|---|---|---|"]
        for cid in dd["capabilities"]:
            m = caps[cid]
            s = capsum.get(cid, {"files": 0, "bytes": 0, "est_tokens": 0, "sources": []})
            extra = f" (QA: {m['web_qa_class']})" if m.get("web_qa_class") else ""
            out.append(f"| `{cid}` | {m['description']}{extra} | {', '.join(s['sources']) or '—'} | {s['files']} | {s['bytes'] / 1024:.1f} | "
                       f"{s['est_tokens']:,} | {m['context_level']} | {m['runtime_type']} | {m['requires_network']} | {m['requires_browser']} | "
                       f"{m['origin']} | {', '.join(m['dependencies']) or '—'} |")
        out.append("")
    with open(os.path.join(AUDIT, "06_DOMAIN_MAPPING.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"05: {len(rows)} rows; 06: {len(caps)} capabilities")


if __name__ == "__main__":
    main()
