"""Third-party license and notice collection (D-002: licenses never block, but are always carried).

`python -m agylite.bundle.notices` reads the staged upstream snapshots and regenerates
third_party/licenses.json (machine-readable, read by provenance) and THIRD_PARTY_NOTICES.md.
"""
import json
import re
import sys
from collections import Counter
from pathlib import Path

from ..paths import repo_root
from .provenance import licenses_file, load_pins
from .rules import (BUNDLED, classify, compile_rules, evidence_dir, load_capabilities,
                    load_rules, read_inventory)

LICENSE_NAME = re.compile(r"^(LICEN[CS]E|COPYING|NOTICE|THIRD[_-]PARTY)", re.I)
COPYRIGHT = re.compile(r"^\s*Copyright\b.*\d{4}.*$", re.I | re.M)


def staging_dir() -> Path:
    return repo_root() / ".staging" / "upstream"


def detect_license(text: str) -> str:
    head = text[:600]
    if "MIT License" in head or "Permission is hereby granted, free of charge" in text:
        return "MIT"
    if "Apache License" in head and "Version 2.0" in head:
        return "Apache-2.0"
    return "UNKNOWN"


def describe(repo: str, root: Path):
    """License id, attribution line and carried license/notice files for one staged repo."""
    files = sorted(p.name for p in root.iterdir() if p.is_file() and LICENSE_NAME.match(p.name))
    if (root / "licenses").is_dir():
        files += sorted(f"licenses/{p.name}" for p in (root / "licenses").iterdir() if p.is_file())
    texts = {name: (root / name).read_text(encoding="utf-8", errors="ignore") for name in files}
    license_id = next((detect_license(t) for n, t in texts.items() if n.upper().startswith("LICEN")), None)
    attribution = None
    for name in sorted(texts, key=lambda n: (not n.upper().startswith("LICEN"), n)):
        m = COPYRIGHT.search(texts[name])
        if m and "copyright owner" not in m.group(0).lower():
            attribution = m.group(0).strip()
            break
    note = None
    if license_id is None:
        manifest = root / ".claude-plugin" / "plugin.json"
        meta = json.loads(manifest.read_text(encoding="utf-8")) if manifest.is_file() else {}
        license_id = meta.get("license", "UNKNOWN")
        author = (meta.get("author") or {}).get("name")
        attribution = attribution or (f"{author} and contributors" if author else None)
        note = "License declared in package metadata; upstream ships no license text."
    return {"license": license_id, "attribution": attribution or f"{repo} contributors",
            "license_files": files, "note": note}


def bundled_counts():
    rules_doc = load_rules()
    compile_rules(rules_doc, load_capabilities())
    counts = Counter()
    for repo, rr in rules_doc["repos"].items():
        for path, _size, _sha in read_inventory(evidence_dir(), repo):
            if classify(rr, path)["decision"] in BUNDLED:
                counts[repo] += 1
    return counts


def generate():
    pins, counts = load_pins(), bundled_counts()
    data = {}
    for repo in sorted(pins):
        info = describe(repo, staging_dir() / repo)
        info.update({"repository": pins[repo]["repo"], "commit_sha": pins[repo]["head"], "bundled_files": counts[repo]})
        data[repo] = info
    licenses_file().parent.mkdir(parents=True, exist_ok=True)
    licenses_file().write_text(json.dumps(data, indent=1, sort_keys=True) + "\n", encoding="utf-8")

    lines = ["# Third-Party Notices", "",
             "Agylite bundles selected content from the upstream projects below "
             "(see `tools/audit/extraction-rules.yaml` and `docs/audit/10_PROVENANCE_LICENSE_AUDIT.md`). "
             "Each project's license and notice files are carried verbatim into the built bundle under "
             "`third_party/<repo>/`. Upstream content remains under its original license.", "",
             "*Generated by `python -m agylite.bundle.notices`. Do not edit by hand.*", "",
             "| Project | Pinned commit | License | Attribution | Bundled files | License/notice files carried |",
             "|---|---|---|---|---:|---|"]
    for repo, info in data.items():
        files = ", ".join(f"`{f}`" for f in info["license_files"]) or "— " + (info["note"] or "")
        lines.append(f"| [{info['repository']}](https://github.com/{info['repository']}) | `{info['commit_sha'][:7]}` | "
                     f"{info['license']} | {info['attribution']} | {info['bundled_files']} | {files} |")
    (repo_root() / "THIRD_PARTY_NOTICES.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return data


if __name__ == "__main__":
    result = generate()
    print(f"{len(result)} upstream projects; licenses: {dict(Counter(v['license'] for v in result.values()))}")
    sys.exit(0 if all(v["license"] != "UNKNOWN" for v in result.values()) else 1)
